language: go
go:
- master

env:
  global:
      - CGO_ENABLED=0
      - GOOS="linux"

addons:
  artifacts: true

sudo: false

services:
 - docker

before_script:
 - go get github.com/gen2brain/go-fitz

script:
 - go build

after_success:
  - bin/docker_push.sh
